development:
  adapter: postgresql
  encoding: unicode
  database: project_development
  pool: 5
  timeout: 5000
  username: 
  password:

test: &TEST
  adapter: postgresql
  database: project_test
  pool: 5
  timeout: 5000
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: 
  password:
